### ISSUE TITLE
Secret support

### ISSUE THREAD

**Issue by guesswh0** [joke2k/django-environ#423]
There is case when it is required to read envs from files e.g. kubernetes mounted secret volume:

```yaml
    spec:
      ...
        volumeMounts:
          - name: webapp-secret
            mountPath: "/mnt/secrets"
            readOnly: true
        imagePullPolicy: Never
      ...
```

I would be happy to see such enhancement!

**Comment by bj00rn** [comment]
FileAwareEnv should take care of this for you unless im mistaken. At least in compose


python
```python
env = environ.FileAwareEnv(
    DJANGO_SECRET_KEY=(str, ""),
 )
```

compose
```yaml
    environment:
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key
    secrets:
      - django_secret_key
 ```
